services:
  rabbitmq:
    image: 'rabbitmq:3.12-management'
    hostname: "rabbitmq"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'rmuser'
      RABBITMQ_DEFAULT_PASS: 'rmpassword'
volumes:
  rabbitmq_data:
